#!/bin/sh
# Make sure all our local dependencies are available.

set -e

BUNDLE=.bundle
BIN=$BUNDLE/binstubs
SCRIPT=$(basename "$0")

# FIX: only sudo if gem home isn't writable

(gem spec bundler -v '~> 1.2.0' > /dev/null 2>&1) || {
  gem install bundler -v '~> 1.2.0' --no-rdoc --no-ri
}

# We don't want old config hanging around.

rm -rf .bundle/config
rm -rf .librarian/puppet/config

# Bundle install unless we're already up to date.

bundle install --binstubs .bundle/bin --path .bundle "$@"
bundle exec librarian-puppet install --path=modules

